services:
  - type: web
    name: crew-accommodations-planner
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: .
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: MAPS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
