-- Migration: Create content_jobs table
-- Purpose: Core job management with status tracking, retry logic, and WordPress integration fields
-- PRD Reference: Functional Requirements 1-11, Database Schema section

-- Create content_jobs table with all required columns
CREATE TABLE IF NOT EXISTS content_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    topic TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'error')),
    prompt_template TEXT,
    model TEXT DEFAULT 'gpt-4',
    retry_count INTEGER DEFAULT 0 CHECK (retry_count >= 0 AND retry_count <= 3),
    claimed_at TIMESTAMPTZ,
    last_error TEXT,
    generated_title TEXT,
    generated_content TEXT,
    wordpress_post_id INTEGER,
    tags TEXT[],
    categories TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add comments for documentation
COMMENT ON TABLE content_jobs IS 'Core job management table for content automation pipeline';
COMMENT ON COLUMN content_jobs.id IS 'Unique identifier for each content job';
COMMENT ON COLUMN content_jobs.topic IS 'The topic/subject for content generation';
COMMENT ON COLUMN content_jobs.status IS 'Current status: pending, processing, completed, error';
COMMENT ON COLUMN content_jobs.prompt_template IS 'Custom prompt template for content generation';
COMMENT ON COLUMN content_jobs.model IS 'OpenAI model to use for generation (default: gpt-4)';
COMMENT ON COLUMN content_jobs.retry_count IS 'Number of retry attempts (max 3)';
COMMENT ON COLUMN content_jobs.claimed_at IS 'Timestamp when job was claimed for processing';
COMMENT ON COLUMN content_jobs.last_error IS 'Last error message if job failed';
COMMENT ON COLUMN content_jobs.generated_title IS 'Title generated by OpenAI';
COMMENT ON COLUMN content_jobs.generated_content IS 'Content generated by OpenAI';
COMMENT ON COLUMN content_jobs.wordpress_post_id IS 'WordPress post ID after successful posting';
COMMENT ON COLUMN content_jobs.tags IS 'Array of tags for WordPress post';
COMMENT ON COLUMN content_jobs.categories IS 'Array of categories for WordPress post';

-- Create indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_content_jobs_status ON content_jobs(status);
CREATE INDEX IF NOT EXISTS idx_content_jobs_claimed_at ON content_jobs(claimed_at);
CREATE INDEX IF NOT EXISTS idx_content_jobs_retry_count ON content_jobs(retry_count);
CREATE INDEX IF NOT EXISTS idx_content_jobs_created_at ON content_jobs(created_at);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_content_jobs_updated_at 
    BEFORE UPDATE ON content_jobs 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
