name: Test GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test step
        run: echo "GitHub Actions is working!"
        
      - name: List files
        run: ls -la
